In [164]:
import pandas

In [165]:
dataset1 = pandas.read_csv('500_Person_Gender_Height_Weight_Index.csv')

In [166]:
dataset1.columns

Index(['Gender', 'Height', 'Weight', 'Index'], dtype='object')

In [167]:
dataset = dataset1[[  'Gender', 'Height', 'Weight'   ]]

In [168]:
dataset

     Gender  Height  Weight
0      Male     174      96
1      Male     189      87
2    Female     185     110
3    Female     195     104
4      Male     149      61
..      ...     ...     ...
495  Female     150     153
496  Female     184     121
497  Female     141     136
498    Male     150      95
499    Male     173     131

[500 rows x 3 columns]

In [169]:
dataset.describe()

           Height      Weight
count  500.000000  500.000000
mean   169.944000  106.000000
std     16.375261   32.382607
min    140.000000   50.000000
25%    156.000000   80.000000
50%    170.500000  106.000000
75%    184.000000  136.000000
max    199.000000  160.000000

In [170]:
# Here Height will decide Weight
# y = Weight

In [171]:
y = dataset[  'Weight'  ]

In [172]:
X = dataset[  'Height'  ]

In [173]:
from keras.models import Sequential

In [174]:
from keras.layers import Dense

In [175]:
# brain = Artificial Nural Network(ANN)

brain = Sequential()

In [176]:
brain.get_config()

{'name': 'sequential_10', 'trainable': True, 'dtype': 'float32', 'layers': []}

In [177]:
# Making Layer
# By default, activation will be LINEAR

brain.add( Dense( units=1, activation="linear" ) )

In [178]:
brain.get_config()

{'name': 'sequential_10',
 'trainable': True,
 'dtype': 'float32',
 'layers': [{'module': 'keras.layers',
   'class_name': 'Dense',
   'config': {'name': 'dense_11',
    'trainable': True,
    'dtype': 'float32',
    'units': 1,
    'activation': 'linear',
    'use_bias': True,
    'kernel_initializer': {'module': 'keras.initializers',
     'class_name': 'GlorotUniform',
     'config': {'seed': None},
     'registered_name': None},
    'bias_initializer': {'module': 'keras.initializers',
     'class_name': 'Zeros',
     'config': {},
     'registered_name': None},
    'kernel_regularizer': None,
    'bias_regularizer': None,
    'kernel_constraint': None,
    'bias_constraint': None},
   'registered_name': None}]}

In [179]:
brain.get_layer

In [180]:
brain.get_weights()

[]

In [181]:
# brain.fit(X , y)

In [182]:
brain.compile(loss='mean_absolute_error'  )

In [183]:
brain.fit(X , y, epochs=6)

Epoch 1/6
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 123.1945
Epoch 2/6
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 118.8807
Epoch 3/6
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 114.0861
Epoch 4/6
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 109.3405
Epoch 5/6
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 109.5577
Epoch 6/6
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 973us/step - loss: 106.9061

In [42]:
brain.predict

In [184]:
brain.get_weights()

[array([[1.2379895]], dtype=float32), array([-0.10514153], dtype=float32)]

In [185]:
brain.predict(  X  )

16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

array([[215.30504],
       [233.87488],
       [228.92291],
       [241.30281],
       [184.3553 ],
       [233.87488],
       [181.87932],
       [190.54524],
       [215.30504],
       [209.11508],
       [241.30281],
       [196.73518],
       [237.58885],
       [191.78323],
       [236.35086],
       [189.30725],
       [194.25922],
       [173.2134 ],
       [178.16534],
       [212.82906],
       [194.25922],
       [189.30725],
       [209.11508],
       [228.92291],
       [212.82906],
       [186.83127],
       [235.11287],
       [231.3989 ],
       [201.68715],
       [221.49498],
       [189.30725],
       [220.25699],
       [241.30281],
       [197.97318],
       [194.25922],
       [233.87488],
       [243.7788 ],
       [178.16534],
       [211.59106],
       [228.92291],
       [216.54301],
       [184.3553 ],
       [194.25922],
       [199.21117],
       [225.20895],
       [228.92291],
       [232.63689],
       [223.97096],
       [199.21117],
       [173.2134 ],
       [207.87709],
       [217.781  ],
       [201.68715],
       [212.82906],
       [242.5408 ],
       [231.3989 ],
       [212.82906],
       [220.25699],
       [202.92514],
       [176.92735],
       [236.35086],
       [174.45137],
       [238.82683],
       [235.11287],
       [216.54301],
       [221.49498],
       [212.82906],
       [207.87709],
       [202.92514],
       [240.06482],
       [189.30725],
       [220.25699],
       [174.45137],
       [222.73297],
       [228.92291],
       [243.7788 ],
       [204.16313],
       [207.87709],
       [217.781  ],
       [223.97096],
       [202.92514],
       [205.40112],
       [235.11287],
       [230.1609 ],
       [207.87709],
       [245.01678],
       [216.54301],
       [179.40334],
       [196.73518],
       [228.92291],
       [220.25699],
       [226.44695],
       [240.06482],
       [219.019  ],
       [243.7788 ],
       [210.35307],
       [175.68936],
       [197.97318],
       [241.30281],
       [235.11287],
       [246.25478],
       [190.54524],
       [199.21117],
       [245.01678],
       [237.58885],
       [241.30281],
       [205.40112],
       [196.73518],
       [223.97096],
       [184.3553 ],
       [185.59328],
       [180.64133],
       [235.11287],
       [237.58885],
       [219.019  ],
       [183.11731],
       [204.16313],
       [180.64133],
       [178.16534],
       [217.781  ],
       [207.87709],
       [231.3989 ],
       [231.3989 ],
       [227.68492],
       [195.4972 ],
       [195.4972 ],
       [240.06482],
       [179.40334],
       [225.20895],
       [190.54524],
       [207.87709],
       [231.3989 ],
       [195.4972 ],
       [206.6391 ],
       [211.59106],
       [226.44695],
       [235.11287],
       [240.06482],
       [211.59106],
       [196.73518],
       [209.11508],
       [206.6391 ],
       [222.73297],
       [201.68715],
       [173.2134 ],
       [243.7788 ],
       [240.06482],
       [173.2134 ],
       [241.30281],
       [207.87709],
       [242.5408 ],
       [173.2134 ],
       [185.59328],
       [207.87709],
       [191.78323],
       [221.49498],
       [225.20895],
       [207.87709],
       [231.3989 ],
       [223.97096],
       [246.25478],
       [227.68492],
       [237.58885],
       [225.20895],
       [212.82906],
       [223.97096],
       [217.781  ],
       [193.02122],
       [186.83127],
       [232.63689],
       [231.3989 ],
       [215.30504],
       [206.6391 ],
       [242.5408 ],
       [243.7788 ],
       [228.92291],
       [210.35307],
       [223.97096],
       [205.40112],
       [232.63689],
       [200.44916],
       [219.019  ],
       [200.44916],
       [222.73297],
       [237.58885],
       [204.16313],
       [206.6391 ],
       [225.20895],
       [199.21117],
       [195.4972 ],
       [174.45137],
       [190.54524],
       [204.16313],
       [175.68936],
       [174.45137],
       [179.40334],
       [194.25922],
       [219.019  ],
       [205.40112],
       [238.82683],
       [227.68492],
       [221.49498],
       [193.02122],
       [225.20895],
       [179.40334],
       [185.59328],
       [179.40334],
       [242.5408 ],
       [236.35086],
       [183.11731],
       [185.59328],
       [183.11731],
       [189.30725],
       [242.5408 ],
       [228.92291],
       [211.59106],
       [176.92735],
       [175.68936],
       [174.45137],
       [196.73518],
       [214.06705],
       [226.44695],
       [188.06926],
       [220.25699],
       [232.63689],
       [191.78323],
       [205.40112],
       [232.63689],
       [211.59106],
       [221.49498],
       [230.1609 ],
       [189.30725],
       [227.68492],
       [219.019  ],
       [179.40334],
       [210.35307],
       [223.97096],
       [204.16313],
       [215.30504],
       [180.64133],
       [220.25699],
       [205.40112],
       [236.35086],
       [219.019  ],
       [226.44695],
       [186.83127],
       [225.20895],
       [175.68936],
       [232.63689],
       [199.21117],
       [189.30725],
       [173.2134 ],
       [209.11508],
       [200.44916],
       [226.44695],
       [200.44916],
       [212.82906],
       [185.59328],
       [209.11508],
       [227.68492],
       [196.73518],
       [201.68715],
       [193.02122],
       [194.25922],
       [181.87932],
       [174.45137],
       [214.06705],
       [190.54524],
       [207.87709],
       [207.87709],
       [179.40334],
       [188.06926],
       [231.3989 ],
       [201.68715],
       [220.25699],
       [231.3989 ],
       [221.49498],
       [235.11287],
       [212.82906],
       [232.63689],
       [238.82683],
       [181.87932],
       [181.87932],
       [205.40112],
       [237.58885],
       [223.97096],
       [185.59328],
       [220.25699],
       [193.02122],
       [184.3553 ],
       [193.02122],
       [226.44695],
       [200.44916],
       [204.16313],
       [207.87709],
       [197.97318],
       [209.11508],
       [173.2134 ],
       [231.3989 ],
       [186.83127],
       [230.1609 ],
       [225.20895],
       [232.63689],
       [221.49498],
       [193.02122],
       [232.63689],
       [226.44695],
       [178.16534],
       [242.5408 ],
       [211.59106],
       [211.59106],
       [222.73297],
       [236.35086],
       [221.49498],
       [222.73297],
       [190.54524],
       [232.63689],
       [175.68936],
       [210.35307],
       [188.06926],
       [235.11287],
       [223.97096],
       [189.30725],
       [231.3989 ],
       [178.16534],
       [183.11731],
       [246.25478],
       [206.6391 ],
       [202.92514],
       [228.92291],
       [202.92514],
       [175.68936],
       [204.16313],
       [212.82906],
       [194.25922],
       [191.78323],
       [206.6391 ],
       [202.92514],
       [233.87488],
       [199.21117],
       [191.78323],
       [211.59106],
       [190.54524],
       [221.49498],
       [210.35307],
       [227.68492],
       [236.35086],
       [200.44916],
       [220.25699],
       [194.25922],
       [227.68492],
       [243.7788 ],
       [197.97318],
       [227.68492],
       [235.11287],
       [215.30504],
       [233.87488],
       [230.1609 ],
       [222.73297],
       [230.1609 ],
       [238.82683],
       [199.21117],
       [186.83127],
       [241.30281],
       [227.68492],
       [174.45137],
       [228.92291],
       [230.1609 ],
       [175.68936],
       [181.87932],
       [186.83127],
       [197.97318],
       [228.92291],
       [201.68715],
       [215.30504],
       [185.59328],
       [175.68936],
       [220.25699],
       [190.54524],
       [217.781  ],
       [196.73518],
       [236.35086],
       [219.019  ],
       [186.83127],
       [225.20895],
       [243.7788 ],
       [180.64133],
       [197.97318],
       [194.25922],
       [185.59328],
       [206.6391 ],
       [222.73297],
       [226.44695],
       [226.44695],
       [188.06926],
       [202.92514],
       [231.3989 ],
       [209.11508],
       [184.3553 ],
       [201.68715],
       [241.30281],
       [215.30504],
       [225.20895],
       [209.11508],
       [238.82683],
       [183.11731],
       [230.1609 ],
       [204.16313],
       [180.64133],
       [205.40112],
       [221.49498],
       [219.019  ],
       [223.97096],
       [199.21117],
       [194.25922],
       [209.11508],
       [188.06926],
       [200.44916],
       [200.44916],
       [219.019  ],
       [241.30281],
       [173.2134 ],
       [230.1609 ],
       [220.25699],
       [215.30504],
       [222.73297],
       [232.63689],
       [231.3989 ],
       [189.30725],
       [204.16313],
       [220.25699],
       [201.68715],
       [185.59328],
       [221.49498],
       [204.16313],
       [207.87709],
       [189.30725],
       [227.68492],
       [232.63689],
       [205.40112],
       [212.82906],
       [225.20895],
       [176.92735],
       [188.06926],
       [230.1609 ],
       [196.73518],
       [180.64133],
       [217.781  ],
       [180.64133],
       [196.73518],
       [200.44916],
       [212.82906],
       [209.11508],
       [225.20895],
       [226.44695],
       [217.781  ],
       [232.63689],
       [216.54301],
       [190.54524],
       [227.68492],
       [221.49498],
       [188.06926],
       [221.49498],
       [179.40334],
       [223.97096],
       [195.4972 ],
       [232.63689],
       [179.40334],
       [199.21117],
       [245.01678],
       [181.87932],
       [190.54524],
       [220.25699],
       [241.30281],
       [206.6391 ],
       [226.44695],
       [202.92514],
       [206.6391 ],
       [186.83127],
       [181.87932],
       [191.78323],
       [212.82906],
       [175.68936],
       [180.64133],
       [232.63689],
       [214.06705],
       [197.97318],
       [231.3989 ],
       [245.01678],
       [221.49498],
       [202.92514],
       [180.64133],
       [245.01678],
       [210.35307],
       [188.06926],
       [185.59328],
       [227.68492],
       [174.45137],
       [185.59328],
       [214.06705]], dtype=float32)