In [1]:
import pandas

In [2]:
dataset = pandas.read_csv('Churn_Modelling.csv')

In [3]:
dataset

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [4]:
dataset.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [5]:
y = dataset[  'Exited' ]

In [6]:
# X = dataset[ [  'CreditScore', 'Geography',
  #     'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
   #    'IsActiveMember', 'EstimatedSalary'  ]   ]

In [7]:


geo = pandas.get_dummies(  dataset['Geography'], drop_first=True  )

In [8]:
gender = pandas.get_dummies(  dataset['Gender'], drop_first=True  )

In [9]:
tenure = pandas.get_dummies(  dataset['Tenure'], drop_first=True  )

In [10]:
product = pandas.get_dummies(  dataset['NumOfProducts'], drop_first=True  )

In [11]:
crCard = pandas.get_dummies(  dataset['HasCrCard'], drop_first=True  )

In [12]:
activeMenber = pandas.get_dummies(  dataset['IsActiveMember'], drop_first=True  )

In [13]:
X = pandas.concat(  [  dataset['CreditScore'], dataset['Age'], dataset['Balance'], dataset['EstimatedSalary'], geo, gender, tenure, product, crCard, activeMenber ], axis=1  )

In [14]:
X

,CreditScore,Age,Balance,EstimatedSalary,Germany,Spain,Male,1,2,3,...,6,7,8,9,10,2,3,4,1,1
0,619,42,0.00,101348.88,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,True
1,608,41,83807.86,112542.58,False,True,False,True,False,False,...,False,False,False,False,False,False,False,False,False,True
2,502,42,159660.80,113931.57,False,False,False,False,False,False,...,False,False,True,False,False,False,True,False,True,False
3,699,39,0.00,93826.63,False,False,False,True,False,False,...,False,False,False,False,False,True,False,False,False,False
4,850,43,125510.82,79084.10,False,True,False,False,True,False,...,False,False,False,False,False,False,False,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,0.00,96270.64,False,False,True,False,False,False,...,False,False,False,False,False,True,False,False,True,False
9996,516,35,57369.61,101699.77,False,False,True,False,False,False,...,False,False,False,False,True,False,False,False,True,True
9997,709,36,0.00,42085.58,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,True
9998,772,42,75075.31,92888.52,True,False,True,False,False,True,...,False,False,False,False,False,True,False,False,True,False
9999,792,28,130142.79,38190.78,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False

In [15]:
# Last layer gives the outcome

In [16]:
from keras.models import Sequential

In [17]:
brain = Sequential()

In [18]:
brain.get_config

In [19]:
brain.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                      ┃ Output Shape             ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
└───────────────────────────────────┴──────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [20]:
from keras.layers import Dense

In [33]:
# Input Dimension is 22. Because 22 columns are there. input_dim=22.   Need to mention in the first layer.
# Here we are adding 5 Neurons. Hence units=5
# It will be the first Layer.

brain.add(  
    Dense(  
            input_dim=22, 
            units=5, 
            activation='relu' ,
            kernel_initializer="zeros" ,
            bias_initializer="zeros"
    )
)

C:\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [22]:
# Param = (22 + 1) * 5
# For eacn unit(nuron), 22 coefficient and 1 bias.

brain.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                      ┃ Output Shape             ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                     │ (None, 5)                │           115 │
└───────────────────────────────────┴──────────────────────────┴───────────────┘

 Total params: 115 (460.00 B)

 Trainable params: 115 (460.00 B)

 Non-trainable params: 0 (0.00 B)

In [34]:
# Layer 2
# 5 input from 1st layer
# Param = (5 + 1) * 5 = 30

brain.add(   Dense(units=5, activation='relu', kernel_initializer="zeros", bias_initializer="zeros") )

In [24]:
brain.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                      ┃ Output Shape             ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                     │ (None, 5)                │           115 │
├───────────────────────────────────┼──────────────────────────┼───────────────┤
│ dense_1 (Dense)                   │ (None, 5)                │            30 │
└───────────────────────────────────┴──────────────────────────┴───────────────┘

 Total params: 145 (580.00 B)

 Trainable params: 145 (580.00 B)

 Non-trainable params: 0 (0.00 B)

In [35]:
# Layer 3

brain.add(   Dense(units=3  , activation='relu', kernel_initializer="zeros", bias_initializer="zeros") )

In [26]:
brain.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                      ┃ Output Shape             ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                     │ (None, 5)                │           115 │
├───────────────────────────────────┼──────────────────────────┼───────────────┤
│ dense_1 (Dense)                   │ (None, 5)                │            30 │
├───────────────────────────────────┼──────────────────────────┼───────────────┤
│ dense_2 (Dense)                   │ (None, 3)                │            18 │
└───────────────────────────────────┴──────────────────────────┴───────────────┘

 Total params: 163 (652.00 B)

 Trainable params: 163 (652.00 B)

 Non-trainable params: 0 (0.00 B)

In [27]:
# Layer 4

brain.add(   Dense(units=1  , activation='sigmoid') )

In [28]:
brain.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                      ┃ Output Shape             ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                     │ (None, 5)                │           115 │
├───────────────────────────────────┼──────────────────────────┼───────────────┤
│ dense_1 (Dense)                   │ (None, 5)                │            30 │
├───────────────────────────────────┼──────────────────────────┼───────────────┤
│ dense_2 (Dense)                   │ (None, 3)                │            18 │
├───────────────────────────────────┼──────────────────────────┼───────────────┤
│ dense_3 (Dense)                   │ (None, 1)                │             4 │
└───────────────────────────────────┴──────────────────────────┴───────────────┘

 Total params: 167 (668.00 B)

 Trainable params: 167 (668.00 B)

 Non-trainable params: 0 (0.00 B)

In [29]:
brain.get_config()

{'name': 'sequential',
 'trainable': True,
 'dtype': 'float32',
 'layers': [{'module': 'keras.layers',
   'class_name': 'InputLayer',
   'config': {'batch_shape': (None, 22),
    'dtype': 'float32',
    'sparse': False,
    'name': 'input_layer'},
   'registered_name': None},
  {'module': 'keras.layers',
   'class_name': 'Dense',
   'config': {'name': 'dense',
    'trainable': True,
    'dtype': 'float32',
    'units': 5,
    'activation': 'relu',
    'use_bias': True,
    'kernel_initializer': {'module': 'keras.initializers',
     'class_name': 'GlorotUniform',
     'config': {'seed': None},
     'registered_name': None},
    'bias_initializer': {'module': 'keras.initializers',
     'class_name': 'Zeros',
     'config': {},
     'registered_name': None},
    'kernel_regularizer': None,
    'bias_regularizer': None,
    'kernel_constraint': None,
    'bias_constraint': None},
   'registered_name': None,
   'build_config': {'input_shape': (None, 22)}},
  {'module': 'keras.layers',
   'class_name': 'Dense',
   'config': {'name': 'dense_1',
    'trainable': True,
    'dtype': 'float32',
    'units': 5,
    'activation': 'relu',
    'use_bias': True,
    'kernel_initializer': {'module': 'keras.initializers',
     'class_name': 'GlorotUniform',
     'config': {'seed': None},
     'registered_name': None},
    'bias_initializer': {'module': 'keras.initializers',
     'class_name': 'Zeros',
     'config': {},
     'registered_name': None},
    'kernel_regularizer': None,
    'bias_regularizer': None,
    'kernel_constraint': None,
    'bias_constraint': None},
   'registered_name': None,
   'build_config': {'input_shape': (None, 5)}},
  {'module': 'keras.layers',
   'class_name': 'Dense',
   'config': {'name': 'dense_2',
    'trainable': True,
    'dtype': 'float32',
    'units': 3,
    'activation': 'relu',
    'use_bias': True,
    'kernel_initializer': {'module': 'keras.initializers',
     'class_name': 'GlorotUniform',
     'config': {'seed': None},
     'registered_name': None},
    'bias_initializer': {'module': 'keras.initializers',
     'class_name': 'Zeros',
     'config': {},
     'registered_name': None},
    'kernel_regularizer': None,
    'bias_regularizer': None,
    'kernel_constraint': None,
    'bias_constraint': None},
   'registered_name': None,
   'build_config': {'input_shape': (None, 5)}},
  {'module': 'keras.layers',
   'class_name': 'Dense',
   'config': {'name': 'dense_3',
    'trainable': True,
    'dtype': 'float32',
    'units': 1,
    'activation': 'sigmoid',
    'use_bias': True,
    'kernel_initializer': {'module': 'keras.initializers',
     'class_name': 'GlorotUniform',
     'config': {'seed': None},
     'registered_name': None},
    'bias_initializer': {'module': 'keras.initializers',
     'class_name': 'Zeros',
     'config': {},
     'registered_name': None},
    'kernel_regularizer': None,
    'bias_regularizer': None,
    'kernel_constraint': None,
    'bias_constraint': None},
   'registered_name': None,
   'build_config': {'input_shape': (None, 3)}}],
 'build_input_shape': (None, 22)}

In [30]:
# Binary classification lass function Keras

brain.compile(loss="binary_crossentropy")

In [31]:
brain.fit(X, y, epochs=20)

Epoch 1/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 794us/step - loss: 1322.3689
Epoch 2/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 587us/step - loss: 0.6409
Epoch 3/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 416us/step - loss: 0.5804
Epoch 4/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 780us/step - loss: 0.5411
Epoch 5/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 550us/step - loss: 0.5252
Epoch 6/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 658us/step - loss: 0.5085
Epoch 7/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 804us/step - loss: 0.5065
Epoch 8/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - loss: 0.5164
Epoch 9/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 921us/step - loss: 0.4918
Epoch 10/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 639us/step - loss: 0.5002
Epoch 11/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - loss: 0.5075
Epoch 12/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 976us/step - loss: 0.5036
Epoch 13/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 888us/step - loss: 0.5022
Epoch 14/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 719us/step - loss: 0.5128
Epoch 15/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step - loss: 0.5046
Epoch 16/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 617us/step - loss: 0.5017
Epoch 17/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 993us/step - loss: 0.5069
Epoch 18/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 766us/step - loss: 0.5071
Epoch 19/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 955us/step - loss: 0.5133
Epoch 20/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 870us/step - loss: 0.4923

In [32]:
# Find KERAS Initializer